<?php

use App\Http\Controllers\Backend\About_ratingController;
use App\Http\Controllers\Backend\AboutController;
use App\Http\Controllers\Backend\AcceptanceController;
use App\Http\Controllers\Backend\AdmissionprocessController;
use App\Http\Controllers\Backend\AdmissionrequirementController;
use App\Http\Controllers\Backend\AdmissionserviceController;
use App\Http\Controllers\Backend\AdmissiontimelineController;
use App\Http\Controllers\Backend\CardController;
use App\Http\Controllers\Backend\Cargo_faqController;
use App\Http\Controllers\Backend\CargoController;
use App\Http\Controllers\Backend\ChoiceController;
use App\Http\Controllers\Backend\ConsultationController;
use App\Http\Controllers\Backend\ContactoneController;
use App\Http\Controllers\Backend\ContacttwoController;
use App\Http\Controllers\Backend\CounselorController;
use App\Http\Controllers\Backend\FaqController;
use App\Http\Controllers\Backend\FinancialadviceController;
use App\Http\Controllers\Backend\FinancialfaqController;
use App\Http\Controllers\Backend\FinancialprocessController;
use App\Http\Controllers\Backend\FinancialrequirementController;
use App\Http\Controllers\Backend\FinancialtimelineController;
use App\Http\Controllers\Backend\FloatingbuttonController;
use App\Http\Controllers\Backend\FooterController;
use App\Http\Controllers\Backend\HeroController;
use App\Http\Controllers\Backend\JourneyController;
use App\Http\Controllers\Backend\LiveController;
use App\Http\Controllers\Backend\OurpartnerController;
use App\Http\Controllers\Backend\OurserviceController;
use App\Http\Controllers\Backend\PartnerController;
use App\Http\Controllers\Backend\PlatformstatController;
use App\Http\Controllers\Backend\SchoolController;
use App\Http\Controllers\Backend\ServiceController;
use App\Http\Controllers\Backend\SocialController;
use App\Http\Controllers\Backend\StandardController;
use App\Http\Controllers\Backend\StatementController;
use App\Http\Controllers\Backend\StudentfaqController;
use App\Http\Controllers\Backend\StudentprocessController;
use App\Http\Controllers\Backend\StudentrequirementController;
use App\Http\Controllers\Backend\StudenttimelineController;
use App\Http\Controllers\Backend\StudentvisaController;
use App\Http\Controllers\Backend\SuccessController;
use App\Http\Controllers\Backend\TeamController;
use App\Http\Controllers\Backend\ValueController;
use App\Http\Controllers\Backend\WeekController;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Route;

Route::get('/user', function (Request $request) {
    return $request->user();
})->middleware('auth:sanctum');


// APIs
Route::get('/hero', [HeroController::class, 'ApiAllHeroes']);
Route::get('/consultation', [ConsultationController::class, 'ApiAllConsultations']);
Route::get('/service', [ServiceController::class, 'ApiAllServices']);
Route::get('/choice', [ChoiceController::class, 'ApiAllChoices']);
Route::get('/success', [SuccessController::class, 'ApiAllSuccesses']);
Route::get('/live', [LiveController::class, 'ApiAllLives']);
Route::get('/partner', [PartnerController::class, 'ApiAllPartners']);
Route::get('/acceptance', [AcceptanceController::class, 'ApiAllAcceptances']);
Route::get('/week', [WeekController::class, 'ApiAllWeeks']);
Route::get('/footer', [FooterController::class, 'ApiAllFooters']);
Route::get('/social', [SocialController::class, 'ApiAllSocials']);
Route::get('/about', [AboutController::class, 'ApiAllAbout']);
Route::get('/statement', [StatementController::class, 'ApiAllStatements']);
Route::get('/value', [ValueController::class, 'ApiAllValues']);
Route::get('/team', [TeamController::class, 'ApiAllTeams']);
Route::get('/journey', [JourneyController::class, 'ApiAllJourneys']);
Route::get('/faq', [FaqController::class, 'ApiAllFaqs']);
Route::get('/cargo', [CargoController::class, 'ApiAllCargoes']);
Route::get('/cargo_faq', [Cargo_faqController::class, 'ApiAllCargoFaqs']);
Route::get('/contactone', [ContactoneController::class, 'ApiAllContactOne']);
Route::get('/contacttwo', [ContacttwoController::class, 'ApiAllContactTwo']);
Route::get('/counselor', [CounselorController::class, 'ApiAllCounselors']);
Route::get('/card', [CardController::class, 'ApiAllCards']);
Route::get('/about_rating', [About_ratingController::class, 'ApiAllAboutRatings']);
Route::get('/ourpartner', [OurpartnerController::class, 'ApiAllOurpartners']);
Route::get('/standard', [StandardController::class, 'ApiAllStandards']);
Route::get('/ourservice', [OurserviceController::class, 'ApiAllOurservices']);
Route::get('/admissionprocess', [AdmissionprocessController::class, 'ApiAllAdmissionprocesses']);
Route::get('/admissionservice', [AdmissionserviceController::class, 'ApiAllAdmissionservices']);
Route::get('/admissionrequirement', [AdmissionrequirementController::class, 'ApiAllAdmissionrequirements']);
Route::get('/admissiontimeline', [AdmissiontimelineController::class, 'ApiAllAdmissiontimelines']);
Route::get('/financialprocess', [FinancialprocessController::class, 'ApiAllFinancialprocesses']);
Route::get('/financialadvice', [FinancialadviceController::class, 'ApiAllFinancialadvice']);
Route::get('/financialrequirement', [FinancialrequirementController::class, 'ApiAllFinancialrequirements']);
Route::get('/financialtimeline', [FinancialtimelineController::class, 'ApiAllFinancialtimelines']);
Route::get('/financialfaq', [FinancialfaqController::class, 'ApiAllFinancialfaqs']);
Route::get('/studentvisa', [StudentvisaController::class, 'ApiAllStudentvisas']);
Route::get('/studentprocess', [StudentprocessController::class, 'ApiAllStudentprocesses']);
Route::get('/studenttimeline', [StudenttimelineController::class, 'ApiAllStudenttimelines']);
Route::get('/studentrequirement', [StudentrequirementController::class, 'ApiAllStudentrequirements']);
Route::get('/studentfaq', [StudentfaqController::class, 'ApiAllStudentfaqs']);
Route::get('/platformstat', [PlatformstatController::class, 'ApiAllPlatformstats']);
Route::get('/school', [SchoolController::class, 'ApiAllSchools']);
Route::get('/floatingbutton', [FloatingbuttonController::class, 'ApiAllFloatingbuttons']);
